spring:
  application:
    name: api

  datasource:
    url: ${DATASOURCE_URL:jdbc:postgresql://localhost:5432/ddi}
    username: ${DATASOURCE_USERNAME:postgres}
    password: ${DATASOURCE_PASSWORD:ddi2505}
    driver-class-name: org.postgresql.Driver

  jpa:
    properties:
      hibernate:
        show_sql: false
        format_sql: true
        jdbc:
          batch_size: 300
        order_updates: true
        order_inserts: true
    hibernate:
      ddl-auto: validate
      dialect: org.hibernate.dialect.PostgreSQLDialect
    open-in-view: false

  jackson:
    serialization:
      fail-on-empty-beans: false
    time-zone: 'Asia/Seoul'

  # 레디스 설정
  data:
    redis:
      host: ${REDIS_HOST:localhost}
      port: ${REDIS_PORT:6379}
      password: ${REDIS_PASSWORD:}

  # Kafka 설정
  kafka:
    bootstrap-servers: ${KAFKA_BOOTSTRAP_SERVERS:localhost:9092}
    schema-registry-url: ${SCHEMA_REGISTRY_URL:http://localhost:8081}
    producer:
      key-serializer: org.apache.kafka.common.serialization.StringSerializer
      value-serializer: io.confluent.kafka.serializers.KafkaAvroSerializer
      properties:
        enable.idempotence: true
        max.in.flight.requests.per.connection: 3
        schema.registry.url: ${SCHEMA_REGISTRY_URL:http://localhost:8081}
        transactional.id: scrape-rss-tx-
        partitioner.class: org.apache.kafka.clients.producer.RoundRobinPartitioner
      acks: all
      retries: 3
      delivery.timeout.ms: 60000 # 전송 타임아웃 (1분)
      request.timeout.ms: 30000 # 요청 타임아웃 (30초)
      retry.backoff.ms: 1000 # 재시도 간격 (1초)
      batch-size: 16384  # 배치 크기 설정 (16KB)
      linger.ms: 5
      buffer-memory: 33554432 # 버퍼 메모리 (32MB)
      compression-type: snappy
    topic:
      news: news-events
      partitions: 3
      replication-factor: 1

cors:
  allowed-origins: http://localhost:3000

jwt:
  secret-key: ubLCgCkqfbqE7PUIWdJUeCkXzsim9ZNKubLCgCkqfbqE7PUIWdJUeCkXzsim9ZNK
  access-token-expire-time: 300
  refresh-token-expire-time: 3600

logging:
  level:
    org.hibernate.SQL: DEBUG
    org.hibernate.type.descriptor.sql.BasicBinder: TRACE

ddi:
  cache:
    ttl: 300

springdoc:
  swagger-ui:
    path: /swagger-ui.html
    enabled: true
  api-docs:
    path: /api-docs
  version: 3.0.0